# Generated by Django 3.0.3 on 2021-02-08 13:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='/images/image.png', null=True, upload_to=api.models.upload_path),
        ),
    ]
